//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.19.0
//     from Assets/Scripts/New Actions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Scripts/New Actions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""New Actions"",
    ""maps"": [
        {
            ""name"": ""inputactions"",
            ""id"": ""9b0aa224-5332-40ab-b97a-2052caa36be6"",
            ""actions"": [
                {
                    ""name"": ""move_right"",
                    ""type"": ""Button"",
                    ""id"": ""5b4ae81b-ed21-4329-8b40-e54d206a2775"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""move_left"",
                    ""type"": ""Button"",
                    ""id"": ""ee1c82ca-4082-4cc9-96fa-7a4f8ece9938"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""move_down"",
                    ""type"": ""Button"",
                    ""id"": ""d1a2ae52-bc46-4e7e-b53c-11f940f1d51e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""move_up"",
                    ""type"": ""Button"",
                    ""id"": ""ae78f149-c22e-4bbd-b22d-6949b4ccebd1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f1ee136f-5344-48df-8a4d-8f4cdbfcddda"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move_right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""36f9dff9-c8c6-4efe-ae1c-17d5d4c29180"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move_right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7b8da8a3-76e1-47f0-bcd6-845cfa73cc1c"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move_left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""271d40ab-d6bb-4837-a330-9a37da3a4ba6"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move_left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8abff37b-c4c4-4931-a1f6-9b9ccd305fa5"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move_down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1cf79927-d897-49a2-b5f3-7121742ccb6b"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move_down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""128daab4-75cb-4752-b5cb-bfbf8b332bb3"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move_up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a92ffd1a-385d-48fe-bf1a-6a194a8e9d6a"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move_up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // inputactions
        m_inputactions = asset.FindActionMap("inputactions", throwIfNotFound: true);
        m_inputactions_move_right = m_inputactions.FindAction("move_right", throwIfNotFound: true);
        m_inputactions_move_left = m_inputactions.FindAction("move_left", throwIfNotFound: true);
        m_inputactions_move_down = m_inputactions.FindAction("move_down", throwIfNotFound: true);
        m_inputactions_move_up = m_inputactions.FindAction("move_up", throwIfNotFound: true);
    }

    ~@PlayerControls()
    {
        UnityEngine.Debug.Assert(!m_inputactions.enabled, "This will cause a leak and performance issues, PlayerControls.inputactions.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // inputactions
    private readonly InputActionMap m_inputactions;
    private List<IInputactionsActions> m_InputactionsActionsCallbackInterfaces = new List<IInputactionsActions>();
    private readonly InputAction m_inputactions_move_right;
    private readonly InputAction m_inputactions_move_left;
    private readonly InputAction m_inputactions_move_down;
    private readonly InputAction m_inputactions_move_up;
    /// <summary>
    /// Provides access to input actions defined in input action map "inputactions".
    /// </summary>
    public struct InputactionsActions
    {
        private @PlayerControls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public InputactionsActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "inputactions/move_right".
        /// </summary>
        public InputAction @move_right => m_Wrapper.m_inputactions_move_right;
        /// <summary>
        /// Provides access to the underlying input action "inputactions/move_left".
        /// </summary>
        public InputAction @move_left => m_Wrapper.m_inputactions_move_left;
        /// <summary>
        /// Provides access to the underlying input action "inputactions/move_down".
        /// </summary>
        public InputAction @move_down => m_Wrapper.m_inputactions_move_down;
        /// <summary>
        /// Provides access to the underlying input action "inputactions/move_up".
        /// </summary>
        public InputAction @move_up => m_Wrapper.m_inputactions_move_up;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_inputactions; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="InputactionsActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(InputactionsActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="InputactionsActions" />
        public void AddCallbacks(IInputactionsActions instance)
        {
            if (instance == null || m_Wrapper.m_InputactionsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InputactionsActionsCallbackInterfaces.Add(instance);
            @move_right.started += instance.OnMove_right;
            @move_right.performed += instance.OnMove_right;
            @move_right.canceled += instance.OnMove_right;
            @move_left.started += instance.OnMove_left;
            @move_left.performed += instance.OnMove_left;
            @move_left.canceled += instance.OnMove_left;
            @move_down.started += instance.OnMove_down;
            @move_down.performed += instance.OnMove_down;
            @move_down.canceled += instance.OnMove_down;
            @move_up.started += instance.OnMove_up;
            @move_up.performed += instance.OnMove_up;
            @move_up.canceled += instance.OnMove_up;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="InputactionsActions" />
        private void UnregisterCallbacks(IInputactionsActions instance)
        {
            @move_right.started -= instance.OnMove_right;
            @move_right.performed -= instance.OnMove_right;
            @move_right.canceled -= instance.OnMove_right;
            @move_left.started -= instance.OnMove_left;
            @move_left.performed -= instance.OnMove_left;
            @move_left.canceled -= instance.OnMove_left;
            @move_down.started -= instance.OnMove_down;
            @move_down.performed -= instance.OnMove_down;
            @move_down.canceled -= instance.OnMove_down;
            @move_up.started -= instance.OnMove_up;
            @move_up.performed -= instance.OnMove_up;
            @move_up.canceled -= instance.OnMove_up;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="InputactionsActions.UnregisterCallbacks(IInputactionsActions)" />.
        /// </summary>
        /// <seealso cref="InputactionsActions.UnregisterCallbacks(IInputactionsActions)" />
        public void RemoveCallbacks(IInputactionsActions instance)
        {
            if (m_Wrapper.m_InputactionsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="InputactionsActions.AddCallbacks(IInputactionsActions)" />
        /// <seealso cref="InputactionsActions.RemoveCallbacks(IInputactionsActions)" />
        /// <seealso cref="InputactionsActions.UnregisterCallbacks(IInputactionsActions)" />
        public void SetCallbacks(IInputactionsActions instance)
        {
            foreach (var item in m_Wrapper.m_InputactionsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InputactionsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="InputactionsActions" /> instance referencing this action map.
    /// </summary>
    public InputactionsActions @inputactions => new InputactionsActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "inputactions" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="InputactionsActions.AddCallbacks(IInputactionsActions)" />
    /// <seealso cref="InputactionsActions.RemoveCallbacks(IInputactionsActions)" />
    public interface IInputactionsActions
    {
        /// <summary>
        /// Method invoked when associated input action "move_right" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMove_right(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "move_left" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMove_left(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "move_down" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMove_down(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "move_up" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMove_up(InputAction.CallbackContext context);
    }
}
